import { useEffect, useState } from 'react';
import { CheckCircle2, Edit3, Mail, Phone, RefreshCw, Search, Shield, Trash2, UserX, X } from 'lucide-react';
import { adminDelete, adminGet, adminPatch } from './adminApi';
import './Customers.css';

const formatDate = (v) => v ? new Date(v).toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' }) : '—';

export default function Customers(){
  const [items,setItems]=useState([]),[search,setSearch]=useState(''),[active,setActive]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[form,setForm]=useState({name:'',phone:'',isActive:true,role:'user'}),[saving,setSaving]=useState(false);
  const load=async()=>{try{setError('');setLoading(true);const q=new URLSearchParams({limit:'100'});if(search)q.set('search',search);if(active)q.set('active',active);const data=await adminGet(`/admin/users?${q}`);setItems(data.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search,active]);
  const open=(user)=>{setSelected(user);setForm({name:user.name||'',phone:user.phone||'',isActive:user.isActive!==false,role:user.role||'user'})};
  const save=async()=>{try{setSaving(true);const updated=await adminPatch(`/admin/users/${selected._id}`,form);setItems(p=>p.map(x=>x._id===updated._id?updated:x));setSelected(updated)}catch(e){setError(e.message)}finally{setSaving(false)}};
  const remove=async(id)=>{if(!window.confirm('Delete this customer permanently?'))return;try{await adminDelete(`/admin/users/${id}`);setItems(p=>p.filter(x=>x._id!==id));setSelected(null)}catch(e){setError(e.message)}};
  return <div className="p4-page"><header className="p4-header"><div><span className="p4-eyebrow">MOTORA / CRM / CUSTOMERS</span><h1>Customers</h1><p>Manage customer access, profile information and account roles.</p></div><button className="p4-btn secondary" onClick={load}><RefreshCw size={15}/> Refresh</button></header>
    <section className="customer-toolbar"><div className="customer-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email or phone"/></div><select value={active} onChange={e=>setActive(e.target.value)}><option value="">All accounts</option><option value="true">Active</option><option value="false">Inactive</option></select><span>{items.length} customers</span></section>
    {error&&<div className="customer-error">{error}</div>}
    <section className="p4-panel"><div className="p4-table-wrap"><table><thead><tr><th>Customer</th><th>Contact</th><th>Account</th><th>Joined</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="5" className="customer-empty">Loading…</td></tr>:items.map(user=><tr key={user._id}><td><strong>{user.name}</strong></td><td><div className="customer-contact"><span><Mail size={12}/>{user.email}</span>{user.phone&&<span><Phone size={12}/>{user.phone}</span>}</div></td><td><div className="customer-account"><span className={user.isActive===false?'customer-status inactive':'customer-status active'}>{user.isActive===false?<UserX size={12}/>:<CheckCircle2 size={12}/>} {user.isActive===false?'Inactive':'Active'}</span><span className="customer-role"><Shield size={11}/>{user.role}</span></div></td><td>{formatDate(user.createdAt)}</td><td><div className="customer-actions"><button onClick={()=>open(user)} title="Manage customer"><Edit3 size={14}/></button><button onClick={()=>remove(user._id)} title="Delete customer"><Trash2 size={14}/></button></div></td></tr>)}{!loading&&!items.length&&<tr><td colSpan="5" className="customer-empty">No customers found.</td></tr>}</tbody></table></div></section>
    {selected&&<div className="customer-overlay" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="customer-modal"><button className="customer-close" onClick={()=>setSelected(null)}><X size={17}/></button><span className="p4-eyebrow">CUSTOMER MANAGEMENT</span><h2>Edit account</h2><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="user">User</option><option value="admin">Admin</option></select></label><label className="customer-toggle"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/><span>Account active</span></label><div className="customer-modal-actions"><button className="p4-btn secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="p4-btn primary" disabled={saving} onClick={save}>{saving?'Saving…':'Save changes'}</button></div></div></div>}
  </div>;
}
