import { useEffect, useState } from 'react';
import { CheckSquare, Edit3, Plus, RefreshCw, Search, Star, Trash2, X } from 'lucide-react';
import { adminDelete, adminGet, adminPatch, adminPost } from './adminApi';
import './Inventory.css';

const blank={brand:'',model:'',variant:'',year:'',price:'',type:'SUV',fuel:'Petrol',transmission:'Automatic',km:'',location:'',status:'Available',featured:false,images:[],description:''};
const money=(v)=>`₹${Number(v||0).toLocaleString('en-IN')}`;

export default function Inventory(){
 const [items,setItems]=useState([]),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blank),[saving,setSaving]=useState(false),[selected,setSelected]=useState([]),[bulkStatus,setBulkStatus]=useState('');
 const load=async()=>{try{setLoading(true);setError('');const q=new URLSearchParams({limit:'100'});if(search)q.set('search',search);if(status)q.set('status',status);const data=await adminGet(`/admin/cars?${q}`);setItems(data.items||[]);setSelected([])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search,status]);
 const open=(car=null)=>{setEditing(car);setForm(car?{...blank,...car,year:car.year||'',price:car.price||'',km:car.km||'',images:Array.isArray(car.images)?car.images:[]}:blank);setModal(true)};
 const change=e=>{const {name,value,type,checked}=e.target;setForm(p=>({...p,[name]:type==='checkbox'?checked:value}))};
 const save=async(e)=>{e.preventDefault();try{setSaving(true);const payload={...form,year:Number(form.year),price:Number(form.price),km:Number(form.km||0)};const data=editing?await adminPatch(`/admin/cars/${editing._id}`,payload):await adminPost('/admin/cars',payload);setItems(p=>editing?p.map(x=>x._id===data._id?data:x):[data,...p]);setModal(false)}catch(e){setError(e.message)}finally{setSaving(false)}};
 const remove=async(id)=>{if(!window.confirm('Delete this vehicle permanently?'))return;try{await adminDelete(`/admin/cars/${id}`);setItems(p=>p.filter(x=>x._id!==id));setSelected(p=>p.filter(x=>x!==id))}catch(e){setError(e.message)}};
 const toggle=(id)=>setSelected(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);
 const toggleAll=()=>setSelected(selected.length===items.length?[]:items.map(x=>x._id));
 const bulk=async()=>{if(!selected.length||(!bulkStatus&&bulkStatus!=='FEATURED_ON'&&bulkStatus!=='FEATURED_OFF'))return;try{const body=bulkStatus==='FEATURED_ON'?{ids:selected,featured:true}:bulkStatus==='FEATURED_OFF'?{ids:selected,featured:false}:{ids:selected,status:bulkStatus};await adminPatch('/admin/cars/bulk',body);await load();setBulkStatus('')}catch(e){setError(e.message)}};
 return <div className="p4-page"><header className="p4-header"><div><span className="p4-eyebrow">MOTORA / INVENTORY</span><h1>Inventory</h1><p>Manage listings, statuses and featured placement in bulk.</p></div><div className="p4-actions"><button className="p4-btn secondary" onClick={load}><RefreshCw size={15}/> Refresh</button><button className="p4-btn primary" onClick={()=>open()}><Plus size={15}/> Add car</button></div></header>
 <section className="inventory-toolbar"><div className="inventory-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search brand, model, variant or location"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All status</option><option>Available</option><option>Reserved</option><option>Sold</option></select>{selected.length>0&&<div className="inventory-bulk"><span>{selected.length} selected</span><select value={bulkStatus} onChange={e=>setBulkStatus(e.target.value)}><option value="">Bulk action</option><option value="Available">Set Available</option><option value="Reserved">Set Reserved</option><option value="Sold">Set Sold</option><option value="FEATURED_ON">Mark Featured</option><option value="FEATURED_OFF">Remove Featured</option></select><button onClick={bulk} disabled={!bulkStatus}>Apply</button></div>}</section>
 {error&&<div className="inventory-error">{error}</div>}
 <section className="p4-panel"><div className="p4-table-wrap"><table><thead><tr><th><button className="inventory-check-all" onClick={toggleAll}><CheckSquare size={15}/></button></th><th>Vehicle</th><th>Year</th><th>Price</th><th>Location</th><th>Status</th><th>Featured</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="8" className="inventory-empty">Loading…</td></tr>:items.map(car=><tr key={car._id}><td><input type="checkbox" checked={selected.includes(car._id)} onChange={()=>toggle(car._id)}/></td><td><strong>{car.brand} {car.model}</strong><small>{car.variant||'No variant'}</small></td><td>{car.year}</td><td>{money(car.price)}</td><td>{car.location}</td><td><span className={`p4-badge ${car.status.toLowerCase()}`}>{car.status}</span></td><td>{car.featured?<Star size={14} fill="currentColor"/>:'—'}</td><td><div className="inventory-actions"><button onClick={()=>open(car)}><Edit3 size={14}/></button><button onClick={()=>remove(car._id)}><Trash2 size={14}/></button></div></td></tr>)}{!loading&&!items.length&&<tr><td colSpan="8" className="inventory-empty">No vehicles found.</td></tr>}</tbody></table></div></section>
 {modal&&<div className="inventory-overlay"><form className="inventory-modal" onSubmit={save}><button type="button" className="inventory-close" onClick={()=>setModal(false)}><X size={17}/></button><span className="p4-eyebrow">{editing?'EDIT VEHICLE':'NEW VEHICLE'}</span><h2>{editing?'Update listing':'Add vehicle'}</h2><div className="inventory-form-grid"><label>Brand<input name="brand" value={form.brand} onChange={change} required/></label><label>Model<input name="model" value={form.model} onChange={change} required/></label><label>Variant<input name="variant" value={form.variant} onChange={change}/></label><label>Year<input type="number" name="year" value={form.year} onChange={change} min="1900" required/></label><label>Price<input type="number" name="price" value={form.price} onChange={change} min="0" required/></label><label>KM<input type="number" name="km" value={form.km} onChange={change} min="0"/></label><label>Type<input name="type" value={form.type} onChange={change} required/></label><label>Fuel<select name="fuel" value={form.fuel} onChange={change}><option>Petrol</option><option>Diesel</option><option>Electric</option><option>Hybrid</option></select></label><label>Transmission<select name="transmission" value={form.transmission} onChange={change}><option>Automatic</option><option>Manual</option></select></label><label>Location<input name="location" value={form.location} onChange={change} required/></label><label>Status<select name="status" value={form.status} onChange={change}><option>Available</option><option>Reserved</option><option>Sold</option></select></label><label className="inventory-check"><input type="checkbox" name="featured" checked={form.featured} onChange={change}/> Featured listing</label></div><label className="inventory-full">Description<textarea name="description" value={form.description} onChange={change} rows="3"/></label><div className="inventory-modal-actions"><button type="button" className="p4-btn secondary" onClick={()=>setModal(false)}>Cancel</button><button className="p4-btn primary" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Create vehicle'}</button></div></form></div>}
 </div>;
}
